INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(1,"Boudin blanc", 18,"MEATANDFISH", 0, 3, "white-sausage.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(2,"Boudin noir", 18,"MEATANDFISH", 0, 3, "blood_sausage.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(3,"Châtaigne", 18,"FRUIT", 0, 3, "chestnut.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(4,"Cornichon", 18,"VEGETABLE", 0, 3, "pickles.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(5,"Marron", 18,"FRUIT", 0, 3, "chestnut-2.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(6,"Chocolat", 12,"FRUIT", 0, 3, "chocolate.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(7,"Coquille Saint-Jacques", 12,"MEATANDFISH", 0, 3, "shells.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(8,"Crevette", 12,"MEATANDFISH", 0, 3, "prawns.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(9,"Fruit de la passion", 12,"FRUIT", 0, 3, "passion-fruit.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(10,"Gingembre", 12,"VEGETABLE", 0, 3, "ginger.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(11,"Kaki", 12,"FRUIT", 0, 3, "food.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(12,"Physalis", 12,"FRUIT", 0, 3, "physalis.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(13,"Amande", 10,"FRUIT", 0, 3, "almonds.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(14,"Cacahuète", 10,"FRUIT", 0, 3, "seasoned-peanuts.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(15,"Chou", 10,"VEGETABLE", 0, 3, "col.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(16,"Noisette", 10,"FRUIT", 0, 3, "hazelnuts.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(17,"Noix de Cajou", 10,"FRUIT", 0, 3, "cashew-cores.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(18,"Noix de Pécan", 10,"FRUIT", 0, 3, "pecans.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(19,"Pistache", 10,"FRUIT", 0, 3, "pistachios.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(20,"Rhubarbe", 10,"VEGETABLE", 0, 3, "rhubarb.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(21,"Blette", 9,"VEGETABLE", 0, 3, "chard.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(22,"Saumon", 9,"MEATANDFISH", 0, 3, "salmon.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(23,"Ail", 8,"VEGETABLE", 0, 3, "garlic.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(24,"Ananas", 8,"FRUIT", 0, 3, "pineapple.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(25,"Aneth", 8,"VEGETABLE", 0, 3, "dill.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(26,"Asperge", 8,"VEGETABLE", 0, 3, "asparagus.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(27,"Avocat", 8,"VEGETABLE", 0, 3, "avocado.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(28,"Basilic", 8,"VEGETABLE", 0, 3, "basil.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(29,"Bergamote", 8,"VEGETABLE", 0, 3, "bergamot.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(30,"Canneberge / Cranberry", 8,"FRUIT", 0, 3, "backdrop.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(31,"Cassis", 8,"FRUIT", 0, 3, "currant2.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(32,"Cerise", 8,"FRUIT", 0, 3, "cherry.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(33,"Champignon", 8,"VEGETABLE", 0, 3, "mushroom.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(34,"Chou de Bruxelles", 8,"VEGETABLE", 0, 3, "brussels-sprouts.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(35,"Coriandre", 8,"VEGETABLE", 0, 3, "real-coriander.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(36,"Echalote", 8,"VEGETABLE", 0, 3, "red-shallots.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(37,"Goyave", 8,"FRUIT", 0, 3, "guavas.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(38,"Grenade", 8,"FRUIT", 0, 3, "pomegranate.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(39,"Groseille", 8,"FRUIT", 0, 3, "currant.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(40,"Kiwi", 8,"FRUIT", 0, 3, "kiwi.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(41,"Menthe", 8,"VEGETABLE", 0, 3, "mint.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(42,"Noix de coco", 8,"FRUIT", 0, 3, "coconut.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(43,"Noix de muscade", 8,"VEGETABLE", 0, 3, "nutmeg.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(44,"Oignon", 8,"VEGETABLE", 0, 3, "onions.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(45,"Origan", 8,"VEGETABLE", 0, 3, "oregano.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(46,"Persil", 8,"VEGETABLE", 0, 3, "parsley.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(47,"Papaye", 8,"FRUIT", 0, 3, "papaya.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(48,"Pastèque", 8,"FRUIT", 0, 3, "watermelon.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(49,"Cresson", 7,"VEGETABLE", 0, 3, "cress.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(50,"Feta", 7,"MILK", 0, 3, "greek-feta-cheese.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(51,"Laitue", 7,"VEGETABLE", 0, 3, "salad.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(52,"Pâtes", 7,"STARCHY", 0, 3, "pasta.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(53,"Riz", 7,"STARCHY", 0, 3, "rice.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(54,"Rutabaga", 7,"VEGETABLE", 0, 3, "kohlrabi.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(55,"Tapioca", 7,"VEGETABLE", 0, 3, "tapioca.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(56,"Agneau", 6,"MEATANDFISH", 0, 3, "lamb-cutlet.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(57,"Aubergine", 6,"VEGETABLE", 0, 3, "eggplant.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(58,"Artichaut", 6,"VEGETABLE", 0, 3, "artichoke.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(59,"Boeuf", 6,"MEATANDFISH", 0, 3, "beef_meat.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(60,"Cannelle", 6,"VEGETABLE", 0, 3, "cinnamon.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(61,"Céleri branche", 6,"VEGETABLE", 0, 3, "celery_branch.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(62,"Champignon de Paris", 6,"VEGETABLE", 0, 3, "mushroom.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(63,"Chèvre frais", 6,"MILK", 0, 3, "goat.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(64,"Chou-fleur", 6,"VEGETABLE", 0, 3, "cauliflower.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(65,"Ciboulette", 6,"VEGETABLE", 0, 3, "chive.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(66,"Citron", 6,"FRUIT", 0, 3, "lemon.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(67,"Clémentine", 6,"FRUIT", 0, 3, "clementine.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(68,"Concombre", 6,"VEGETABLE", 0, 3, "cucumbers.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(69,"Courge butternut (Doubeurre)", 6,"VEGETABLE", 0, 3, "butternut.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(70,"Cumin", 6,"VEGETABLE", 0, 3, "cumin.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(71,"Curry", 6,"VEGETABLE", 0, 3, "turmeric.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(72,"Emmental ou Gruyère", 6,"MILK", 0, 3, "emmental.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(73,"Endive", 6,"VEGETABLE", 0, 3, "chicory.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(74,"Fenouil", 6,"VEGETABLE", 0, 3, "fennel.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(75,"Figue", 6,"FRUIT", 0, 3, "figs.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(76,"Fraise", 6,"FRUIT", 0, 3, "strawberries.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(77,"Framboise", 6,"FRUIT", 0, 3, "raspberry.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(78,"Jambon blanc", 6,"MEATANDFISH", 0, 3, "ham.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(79,"Topinambour", 4,"FRUIT", 0, 3, "jerusalem-artichoke.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(80,"Litchi", 6,"FRUIT", 0, 3, "lychee.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(81,"Lotte", 6,"MEATANDFISH", 0, 3, "monkfish.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(82,"Maïs", 6,"VEGETABLE", 0, 3, "corn.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(83,"Mandarine", 6,"FRUIT", 0, 3, "tangerines.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(84,"Mangue", 6,"FRUIT", 0, 3, "mango.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(85,"Melon", 6,"FRUIT", 0, 3, "melon.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(86,"Mozzarella", 6,"MILK", 0, 3, "mozarella.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(87,"Mûre", 6,"FRUIT", 0, 3, "blackberry.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(88,"Myrtille", 6,"FRUIT", 0, 3, "blueberry.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(89,"Navet", 6,"VEGETABLE", 0, 3, "turnip.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(90,"Orange", 6,"FRUIT", 0, 3, "orange.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(91,"Parmesan", 6,"MILK", 0, 3, "parmesan.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(92,"Patisson", 6,"VEGETABLE", 0, 3, "patisson.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(93,"Pamplemousse / Pomelos", 6,"FRUIT", 0, 3, "grapefruit.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(94,"Poivron", 6,"VEGETABLE", 0, 3, "peppers.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(95,"Poulet", 6,"MEATANDFISH", 0, 3, "chicken.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(96,"Radis", 6,"VEGETABLE", 0, 3, "radishes.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(97,"Salsifis", 6,"VEGETABLE", 0, 3, "salsify.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(98,"Thon", 6,"MEATANDFISH", 0, 3, "tuna.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(99,"Thym", 6,"VEGETABLE", 0, 3, "thyme.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(100,"Tomate", 6,"VEGETABLE", 0, 3, "tomatoes.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(101,"Vache qui rit / Kiri", 6,"MILK", 0, 3, "cow.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(102,"Vanille", 6,"FRUIT", 0, 3, "vanilla.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(103,"Abricot", 4,"FRUIT", 0, 3, "apricots.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(104,"Banane", 4,"FRUIT", 0, 3, "banana.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(105,"Betterave", 4,"VEGETABLE", 0, 3, "beetroot.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(106,"Brocoli", 4,"VEGETABLE", 0, 3, "broccoli.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(107,"Brugnon / Nectarine", 4,"FRUIT", 0, 3, "nectarines.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(108,"Carotte", 4,"VEGETABLE", 0, 3, "carrots.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(109,"Céleri rave", 4,"VEGETABLE", 0, 3, "celery.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(110,"Citrouille", 4,"VEGETABLE", 0, 3, "pumpkin.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(111,"Coing", 4,"FRUIT", 0, 3, "quince.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(112,"Courgette", 4,"VEGETABLE", 0, 3, "zucchini.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(113,"Epinard", 4,"VEGETABLE", 0, 3, "spinach.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(114,"Haricots verts", 4,"VEGETABLE", 0, 3, "green_bean.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(115,"Mirabelle", 4,"FRUIT", 0, 3, "yellow-plums.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(116,"Raisin", 4,"FRUIT", 0, 3, "grapes.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(117,"Panais", 4,"VEGETABLE", 0, 3, "parsnips.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(118,"Patate douce", 4,"VEGETABLE", 0, 3, "sweet-potato.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(119,"Pêche", 4,"FRUIT", 0, 3, "peach.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(120,"Petit pois", 4,"VEGETABLE", 0, 3, "pea.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(121,"Poire", 4,"FRUIT", 0, 3, "pear.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(122,"Poireau", 4,"VEGETABLE", 0, 3, "leek.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(123,"Pomme", 4,"FRUIT", 0, 3, "apple.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(124,"Pomme de terre", 4,"VEGETABLE", 0, 3, "potatoes.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(125,"Potimarron / Potiron", 4,"VEGETABLE", 0, 3, "potimarron.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(126,"Prune", 4,"FRUIT", 0, 3, "plums.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(127,"Pruneau", 4,"FRUIT", 0, 3, "dried-apricots.jpg");
INSERT INTO Food(id,name ,minYear, type, introduced, feedback, image) VALUES(128,"Quetsche", 4,"FRUIT", 0, 3, "quetsche.jpg");